// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhnHrkBCdSur2npfJKmh9Z046kWttIOmg',
    appId: '1:350856242261:web:17f6326a0c38b6fa0060dc',
    messagingSenderId: '350856242261',
    projectId: 'gorillagrab-731a2',
    authDomain: 'gorillagrab-731a2.firebaseapp.com',
    storageBucket: 'gorillagrab-731a2.appspot.com',
    measurementId: 'G-5MRP0KPSSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx1UD6CbFQs2cbfwHR9S9gmbK6CL2b1IA',
    appId: '1:350856242261:android:e71e0647104aea320060dc',
    messagingSenderId: '350856242261',
    projectId: 'gorillagrab-731a2',
    storageBucket: 'gorillagrab-731a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsLbefZoeqFzS4r5IAgInqfOlu6iC5VPU',
    appId: '1:350856242261:ios:6a34ae0951b0cf6f0060dc',
    messagingSenderId: '350856242261',
    projectId: 'gorillagrab-731a2',
    storageBucket: 'gorillagrab-731a2.appspot.com',
    iosBundleId: 'com.example.gorillaGrab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsLbefZoeqFzS4r5IAgInqfOlu6iC5VPU',
    appId: '1:350856242261:ios:c9b93cc9727329210060dc',
    messagingSenderId: '350856242261',
    projectId: 'gorillagrab-731a2',
    storageBucket: 'gorillagrab-731a2.appspot.com',
    iosBundleId: 'com.example.gorillaGrab.RunnerTests',
  );
}
